services:
  neo-service:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: neo-service
    image: neo-service
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - redis
    networks:
      - neo-network
    restart: unless-stopped

  redis:
    image: redis:alpine
    container_name: neo-redis
    ports:
      - "6380:6379"
    volumes:
      - redis-data:/data
    networks:
      - neo-network
    command: redis-server --appendonly yes
    restart: unless-stopped

networks:
  neo-network:
    driver: bridge

volumes:
  redis-data: