version: '3.8'

services:
  neonchat-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: neonchat-service
    container_name: neonchat-service
    ports:
      - "8000:8000"
      - "8001:8001"
    env_file: .env
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - neonchat-network
    restart: "no"
    depends_on:
      - redis

  redis:
    image: redis:alpine
    container_name: neonchat-redis
    ports:
      - "6380:6379"
    networks:
      - neonchat-network
    restart: "no"

networks:
  neonchat-network:
    driver: bridge