version: '3.8'

services:
  neonchat-service:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - GROQ_API_KEY=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
      - NEO_API_KEY=api_r0g-KXFkFv2nYSlxN8kpbrB-JQXPGuh4Ji4nYqPU
      - TELEGRAM_BOT_TOKEN=8062568450:AAG_S--VP92MeL6JW1ONtQ0XlkoffbMrsLw
    networks:
      - neonchat-network

networks:
  neonchat-network:
    name: neonchat-network