# Продакшен конфигурация
version: '3.8'

services:
  neo-service:
    container_name: neo-service-prod
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
    networks:
      - prod-network

networks:
  prod-network:
    name: prod-network 